### PR TITLE
Panda issue 10 lcov

### PR DESCRIPTION
**Pull request by 74monkeys**
New puppet module to install lcov v 1.13

### CODE REVIEW

**Comment by chrisjwilliams** [comment]
Can you make it install the system lcov version unless this version is less than 1.13, in which case use this techinqiue

**Comment by 74monkeys** [comment]
Hi Chris,
I've just pushed some more code for you to look at.

To avoid having to create custom facts I have come up with a solution. Not perfect but it should work.
Essentially, using facts that are available, I check for the Distribution and OS version. If it is Debian, and 14. then I do a manual install of lcov 1.13 otherwise we use the standard install method.

It's not perfect, but is perhaps better than a blanket instal of 1.13 regardless.

Let me know what you think.

**Comment by 74monkeys** [comment]
Ok, I'll update the code and re-push.

**Comment by 74monkeys** [comment]
I've rolled the different modules into one lcov module.
Operates the same as before but uses sub mods.

**Comment by chrisjwilliams** [comment]
Ensure lcov version 1.13 is installed as a minimum on debian

**Pull request merged**
